### ISSUE TITLE
可能是个小bug

### ISSUE THREAD

**Issue by Passerby-D** [Nranphy/nonebot_plugin_offline_mahjong_helper#1]
在使用“/雀魂查询”的时候，会报错没有template/style.css这个文件，手动添加后功能正常运行
好像是没有检测并自动生成文件

**Comment by Nranphy** [comment]
感谢issue捉虫。我在上传PYPI的时候忘记将非python文件一起打包，才造成了style.css文件丢失。稍后我会改进插件内容，并再次在PYPI上发版，我会在本issue下再次回复。
在此之前，你可以直接下载本仓库源码手动放入bot插件文件夹下，谢谢!!Ou<

**Comment by Nranphy** [comment]
PYPI和github均已发布修改后的版本，两种方式均可正常安装插件并使用。
